### ISSUE TITLE
Maximum call stack size exceeded, possibly due to self-referencing type

### ISSUE THREAD

**Issue by mterrel** [relay-tools/relay-compiler-language-typescript#44]
When I run relay-compiler while using this plugin to generate TypeScript output, I get the following output and error:
```
> relay-compiler --src ./frontend/src --schema mydb_schema.graphql --language typescript --artifactDirectory relay-generated

Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
HINT: pass --watch to keep watching for changes.

Writing ts
ERROR:
Error writing modules:
RangeError: Maximum call stack size exceeded
    at Object.createIdentifier (/src/node_modules/typescript/lib/typescript.js:48807:30)
    at transformGraphQLEnumType (/src/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:55:42)
    at transformNonNullableInputType (/src/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:79:16)
    at transformInputType (/src/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:63:13)
    at /src/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:89:30
    at Array.map (<anonymous>)
    at transformNonNullableInputType (/src/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:86:14)
    at transformInputType (/src/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:63:13)
    at /src/node_modules/relay-compiler-language-typescript/lib/TypeScriptTypeTransformers.js:89:30
    at Array.map (<anonymous>)
```

Although I haven't yet created a minimal repro of the issue, the crash is caused when I use a particular type as input parameter to a query. The query is:
```js
const query = graphql`
    query DashboardRepoQuery($filter: DbRepoFilter) {
        allDbRepos(filter: $filter) {
            nodes {
                slug
            }
        }
    }
`;
```
And the DbRepoFilter type (which is auto-generated by Postgraphile) is:
```
input DbRepoFilter {
  """Filter by the object’s `slug` field."""
  slug: StringFilter

  """Filter by the object’s `content` field."""
  content: JSONFilter

  """Checks for all expressions in this list."""
  and: [DbRepoFilter!]

  """Checks for any expressions in this list."""
  or: [DbRepoFilter!]

  """Negates the expression."""
  not: DbRepoFilter
}
```

If this info isn't sufficient, let me know and I can try to create a simpler and more self-contained repro.

**Comment by mterrel** [comment]
I just created a pull request that fixes the issue for me. I wasn't familiar enough with the structure of the current unit tests to easily add a new test case that specifically covers the self-referencing type issue described here. However, the existing snapshot unit tests do cover the new format of the output.

**Comment by waterfoul** [comment]
I've hit this one as well and can confirm it's a problem with self referencing types

**Comment by alloy** [comment]
Apologies for how long it took me to find the time.
